In [3]:
import torch
from torch.nn import Linear,ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [4]:
myLayer=Linear(in_features=10,out_features=5,bias=True)

In [5]:
inp=Variable(torch.randn(1,10))
myLayer=Linear(in_features=10,out_features=5,bias=True)
myLayer(inp)

tensor([[ 0.2000,  1.1000, -0.0106, -0.3661, -0.2183]],
       grad_fn=<AddmmBackward>)

In [6]:
myLayer.weight

Parameter containing:
tensor([[-1.7796e-01, -3.0797e-01, -2.6798e-01, -2.0126e-01,  1.9014e-01,
          2.0522e-01,  8.2967e-03, -1.2184e-02,  1.6774e-01, -1.3371e-01],
        [ 1.8277e-01,  9.4809e-05, -2.5673e-01,  2.3934e-02, -4.2928e-02,
         -1.4173e-01,  2.2325e-01,  2.6879e-01,  2.3357e-01,  2.0078e-01],
        [ 3.1727e-02,  1.8388e-01, -2.5330e-01,  1.7116e-01, -1.3964e-01,
         -8.5110e-02, -5.5801e-02, -1.6585e-01, -2.8756e-01, -3.0704e-01],
        [-2.2997e-01, -2.1538e-01, -1.2671e-01, -5.9669e-02, -1.6693e-01,
          2.4492e-01,  1.7415e-02,  1.9633e-02, -2.6906e-01,  1.2420e-01],
        [-3.8771e-02, -2.4383e-01,  2.6129e-01, -2.5943e-02,  1.2801e-01,
         -2.4431e-01, -9.8205e-02,  9.3562e-02,  3.1577e-01, -7.6169e-02]],
       requires_grad=True)

In [7]:
myLayer.bias

Parameter containing:
tensor([-0.2372,  0.0950, -0.2348,  0.1467, -0.3047], requires_grad=True)

In [8]:
myLayer1=Linear(10,5)
myLayer2=Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[-0.0828, -0.0191]], grad_fn=<AddmmBackward>)

In [11]:
#비선형 함수

from torch.nn import ReLU
import torch
 
sample_data=torch.Tensor([[1,2,-1,-1]])
myRelu=ReLU()
print(myRelu(sample_data))

tensor([[1., 2., 0., 0.]])


In [12]:
#딥러닝 구축

class MyFirstNetwork(nn.Module):
    
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__()
        self.layer1=nn.Linear(input_size,hidden_size)
        self.layer2=nn.Linear(hidden_size,output_size)
        
        
    def forward(self,input):
        out=self.layer1(input)
        out=nn.ReLU(out)
        out=self.layer2(out)
        return out

In [13]:
MyFirstNetwork()

TypeError: __init__() missing 3 required positional arguments: 'input_size', 'hidden_size', and 'output_size'

In [14]:
 #오차함수
    
loss=nn.MSELoss()
input=Variable(torch.randn(3,5),requires_grad=True)
target=Variable(torch.randn(3,5))
output=loss(input,target)
output.backward()

In [17]:
# 교차 엔트로피

def cross__entropy(true_label,prediction):

    if true_label==1:
        return -log(prediction)
    else:
        return -log(1-prediction)
    
loss=nn.CrossEntropyLoss()
input=Variable(torch.randn(3,5),requires_grad=True)
target=Variable(torch.LongTensor(3).random_(5))
output=loss(input,target)
output.backward()

In [19]:
# 옵티마이저

import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

NameError: name 'model' is not defined